version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    # Update all the dependencies:
    # Update the direct dependencies and not the indirect ones,
    # since there are too many ones, and dependabot reaches its 1h timeout most of the time):
    # - direct: explicitly defined dependencies in the Cargo.toml file
    # - indirect: transient dependencies in the Cargo.lock file
    allow:
      - dependency-type: direct
    groups:
      cargo:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "sunday"
