app = "brioche-registry"
primary_region = "sea"

[build]

[env]
BRIOCHE_REGISTRY_PROXY_LAYERS = "1"
LOG_FORMAT = "json"

[http_service]
internal_port = 2000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[http_service.concurrency]
type = "requests"
hard_limit = 1000
soft_limit = 500

[[vm]]
memory = "2gb"
cpu_kind = "shared"
cpus = 1
